import React, { useEffect, useMemo, useState } from "react";
import AdvisoryPanel from "./AdvisoryPanel";
import TrackMap from "./TrackMap";

const API = process.env.REACT_APP_API_URL || "http://127.0.0.1:8000";
const steps = ["T-24h", "T-12h", "T-6h", "Landfall"];
export default function App() {
  const [scenario, setScenario] = useState(null), [simulation, setSimulation] = useState(null), [index, setIndex] = useState(0), [tab, setTab] = useState("risk"), [language, setLanguage] = useState("English"), [advisory, setAdvisory] = useState(null), [loading, setLoading] = useState(false), [status, setStatus] = useState("Connecting");
  useEffect(() => { fetch(`${API}/api/mock-scenario`).then((r) => r.ok ? r.json() : Promise.reject()).then((data) => { setScenario(data); setStatus("Live API"); }).catch(() => fetch("/mockData.json").then((r) => r.json()).then((data) => { setScenario(data); setStatus("Offline scenario"); })); }, []);
  useEffect(() => { if (!scenario) return; fetch(`${API}/api/simulate-track`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ timeline_step: steps[index] }) }).then((r) => r.ok ? r.json() : Promise.reject()).then(setSimulation).catch(() => setSimulation(offline(scenario, index))); }, [scenario, index]);
  const highest = useMemo(() => simulation?.ward_risks?.[0], [simulation]);
  const generate = async () => { if (!highest) return; setLoading(true); const assigned = simulation.routes.find((route) => route.ward_id === highest.ward_id)?.route?.shelter_name; const payload = { ward_name: highest.ward_name, risk_level: highest.risk_level, blocked_roads: simulation.blocked_roads, assigned_shelter: assigned, language }; try { const r = await fetch(`${API}/api/generate-advisory`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) throw Error(); setAdvisory(await r.json()); } catch { setAdvisory({ advisory: `${highest.ward_name} is at ${highest.risk_level} cyclone risk. Avoid ${simulation.blocked_roads.join(", ") || "flood-prone roads"} and report to ${assigned || "the nearest designated shelter"}. Keep emergency supplies ready and follow official updates.`, locale: "en-IN", source: "browser fallback" }); } finally { setLoading(false); } };
  useEffect(() => { setAdvisory(null); }, [simulation, language]);
  return <main><header><h1>CycloneShield AI</h1><small className="status">● {status}</small></header><section className="timeline"><b>{steps[index]}</b><input aria-label="Timeline" type="range" min="0" max="3" value={index} onChange={(e) => setIndex(+e.target.value)}/><div>{steps.map((step, i) => <button key={step} className={i === index ? "active" : ""} onClick={() => setIndex(i)}>{step}</button>)}</div></section><section className="dashboard"><div className="mapbox"><TrackMap scenario={scenario} simulation={simulation}/><p className="legend">Green: safe route · Red dashed: flooded road · Ward colours: Low → Critical</p></div><aside><nav>{[["risk", "Ward risks"], ["advisory", "Advisories"], ["audit", "Relief audit"]].map(([key, name]) => <button key={key} onClick={() => setTab(key)} className={tab === key ? "selected" : ""}>{name}</button>)}</nav>{tab === "risk" && <Risk simulation={simulation}/>} {tab === "advisory" && <AdvisoryPanel advisory={advisory} language={language} setLanguage={setLanguage} generate={generate} loading={loading}/>} {tab === "audit" && <Audit simulation={simulation}/>}</aside></section></main>;
}
function Risk({ simulation }) { return <section className="panel"><h2>Ward risk summary</h2>{!simulation ? "Calculating…" : <>{simulation.ward_risks.map((risk) => <article className="risk" key={risk.ward_id}><b>{risk.ward_name}</b><span className={`pill ${risk.risk_level}`}>{risk.risk_level} · {risk.risk_score}</span><small>{risk.distance_to_track_km} km from cyclone centre · {[...risk.affected_assets.hospitals, ...risk.affected_assets.power_substations].join(" · ") || "No catalogued assets"}</small></article>)}<p className="warning">Blocked roads: {simulation.blocked_roads.join(", ") || "None"}</p></>}</section>; }
function Audit({ simulation }) { const p = simulation?.parametric_payout, a = simulation?.active_track_point; return <section className="panel"><h2>Parametric relief trigger audit</h2>{!p ? "Awaiting forecast…" : <><b className={p.triggered ? "released" : "pending"}>{p.status}</b><p>Wind: {a.wind_speed_kmh} km/h<br/>Rainfall: {a.rainfall_24h_mm} mm<br/>Surge: {a.surge_height_m} m</p><small className="hash">SHA-256: {p.sha256}</small></>}</section>; }
function offline(scenario, index) { const active_track_point = scenario.cyclone_track[index], blocked = active_track_point.wind_speed_kmh >= 90 ? ["beach-road", "harbour-road"] : [], names = Object.fromEntries(scenario.road_network.edges.map((e) => [e.id, e.name])); return { active_track_point, flooded_road_ids: blocked, blocked_roads: blocked.map((id) => names[id]), routes: [], ward_risks: scenario.wards.map((ward, i) => ({ ward_id: ward.id, ward_name: ward.name, risk_level: i < 2 ? "High" : "Moderate", risk_score: 72 - i * 7, distance_to_track_km: 4 + i * 3, affected_assets: ward.critical_assets })), parametric_payout: { triggered: active_track_point.wind_speed_kmh > 90, status: active_track_point.wind_speed_kmh > 90 ? "TIER_1_DISASTER_LIQUIDITY_RELEASED" : "PENDING", sha256: "Available with backend" } }; }
